# Generated by Django 4.2.13 on 2024-06-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_code', models.CharField(max_length=12, unique=True)),
                ('recipient', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('num_items', models.IntegerField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
            ],
        ),
    ]
