# Generated by Django 4.2.13 on 2024-06-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
